/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.idealunited.gateway.dao.impl;

import java.util.HashMap;
import java.util.Map;

import com.idealunited.gateway.dao.GatewayRequestDAO;
import com.idealunited.gateway.model.GatewayRequest;
import com.idealunited.inf.dao.impl.BaseDAOImpl;

public class GatewayRequestDAOImpl extends BaseDAOImpl<GatewayRequest>
		implements GatewayRequestDAO {

	@Override
	public GatewayRequest queryGatewayRequest(Long memberCode, String orderId) {
		Map queryParams = new HashMap();
		queryParams.put("orderId", orderId);
		queryParams.put("memberCode", memberCode);
		return (GatewayRequest) super.findObjectByCriteria(
				"queryByMemberCodeAndOrderId", queryParams);
	}
}