/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.idealunited.gateway.dao.impl;

import java.util.List;

import com.idealunited.gateway.dao.GatewayResponseDAO;
import com.idealunited.gateway.model.GatewayResponse;
import com.idealunited.inf.dao.impl.BaseDAOImpl;

public class GatewayResponseDAOImpl extends BaseDAOImpl<GatewayResponse>
		implements GatewayResponseDAO {

	@Override
	public void updateSuccessByOrderNo(GatewayResponse gatewayResponse) {
		// TODO Auto-generated method stub
		this.getSqlMapClientTemplate().update(
				"gatewayresponse.updateSuccessByOrderNo", gatewayResponse);
	}

	@Override
	public void updateFailByOrderNo(GatewayResponse gatewayResponse) {
		// TODO Auto-generated method stub
		this.getSqlMapClientTemplate().update(
				"gatewayresponse.updateFailByOrderNo", gatewayResponse);
	}

	@Override
	public boolean updateFailByResponseNo(Long responseNo) {
		return getSqlMapClientTemplate().update(
				"gatewayresponse.updateFailByResponseNo", responseNo) == 1;
	}

	@Override
	public boolean updateSuccessByResponseNo(Long responseNo) {
		return getSqlMapClientTemplate().update(
				"gatewayresponse.updateSuccessByResponseNo", responseNo) == 1;
	}

	@Override
	public List<GatewayResponse> queryByOrderNo(Long tradeOrderNo) {
		return getSqlMapClientTemplate().queryForList(
				"gatewayresponse.findByOrderNo", tradeOrderNo);
	}
}