package com.idealunited.fi.commons;

public enum CountryCodeEnum {
	
	ALB	("ALB","8","阿尔巴尼亚 Albania"),
	DZA	("DZA","12","阿尔及利亚 Algeria"),
	AFG	("AFG","4","阿富汗 Afghanistan"),
	ARG	("ARG","32","阿根廷 Argentina"),
	ARE	("ARE","784","阿闻酋 United Arab Emirates"),
	ABW	("ABW","533","阿鲁巴 Aruba "),
	OMN	("OMN","512","阿曼 Oman"),
	AZE	("AZE","31","阿塞拜疆 Azerbaijan"),
	EGY	("EGY","818","埃及 Egypt "),
	ETH	("ETH","231","埃塞俄比亚 Ethiopia"),
	IRL	("IRL","372","爱尔兰 Ireland"),
	EST	("EST","233","爱沙尼亚 Estonia"),
	AND	("AND","20","安道尔 Andorra"),
	AGO	("AGO","24","安哥拉 Angola"),
	AIA	("AIA","660","安圭拉 Anguilla"),
	ATG	("ATG","28","安提瓜和巴布达 Antigua and Barbuda"),
	AUT	("AUT","40","奥地利 Austria"),
	AUS	("AUS","36","澳大利亚 Australia"),
	MAC	("MAC","446","澳门 Macau"),
	BRB	("BRB","52","巴巴多斯 Barbados"),
	PNG	("PNG","598","巴布亚新几内亚 Papua New Guinea"),
	BHS	("BHS","44","巴哈马 Bahamas"),
	PAK	("PAK","586","巴基斯坦 Pakistan"),
	PRY	("PRY","600","巴拉圭 Paraguay"),
	PSE	("PSE","275","巴勒斯坦 Palestine"),
	BHR	("BHR","48","巴林 Bahrain"),
	PAN	("PAN","591","巴拿马 Panama"),
	BRA	("BRA","76","巴西 Brazil"),
	BLR	("BLR","112","白俄罗斯 Belarus"),
	BMU	("BMU","60","百慕大 Bermuda"),
	BGR	("BGR","100","保加利亚 Bulgaria"),
	MNP	("MNP","580","北马里亚纳 Northern Marianas"),
	PLW	("PLW","585","帕劳 Palau"),
	BEN	("BEN","204","贝宁 Benin"),
	BEL	("BEL","56","比利时 Belgium"),
	ISL	("ISL","352","冰岛 Iceland"),
	PRI	("PRI","630","波多黎各 Puerto Rico"),
	POL	("POL","616","波兰 Poland"),
	BOL	("BOL","68","玻利维亚 Bolivia"),
	BIH	("BIH","70","波斯尼亚和黑塞哥 维那 Bosnia and Herzegovina"),
	BWA	("BWA","72","博茨瓦纳 Botswana"),
	BLZ	("BLZ","84","伯利兹 Belize"),
	BTN	("BTN","64","不丹 Bhutan"),
	BFA	("BFA","854","布基纳法索 Burkina Faso"),
	BDI	("BDI","108","布隆迪 Burundi"),
	BVT	("BVT","74","布维岛 Bouvet Island"),
	PRK	("PRK","408","朝鲜 Korea,Democratic People's Republic of Korea "),
	GNQ	("GNQ","226","赤道几内亚	 Equatorial Guinea"),
	DNK	("DNK","208","丹麦 Denmark"),
	DEU	("DEU","276","德国 Germany"),
	TMP	("TMP","626","东帝汶 East Timor"),
	TGO	("TGO","768","多哥 Togo"),
	DOM	("DOM","214","多米尼加共和国 Dominican Republic"),
	DMA	("DMA","212","多米尼克Dominica"),
	RUS	("RUS","643","俄罗斯联邦Russia Federation"),
	ECU	("ECU","218","厄瓜多尔 Ecuador"),
	ERI	("ERI","232","厄立特里亚 Eritrea"),
	FRA	("FRA","250","法国 France"),
	FRO	("FRO","234","法罗群岛 Faroe	 Islands"),
	PYF	("PYF","258","法属波利尼西亚 French Polynesia"),
	GUF	("GUF","254","法属圭亚那 French Guiana"),
	ATF	("ATF","260","法属南部领土 French Southern Territo-ries"),
	VAT	("VAT","336","梵蒂冈 Vatican"),
	PHL	("PHL","608","菲律宾 Philippines"),
	FJI	("FJI","242","斐济 Fiji"),
	FIN	("FIN","246","芬兰 Finland"),
	CPV	("CPV","132","佛得角 Cape Verde"),
	GMB	("GMB","270","冈比亚Gambia"),
	COD	("COD","180","刚果（金）Congo, 	the Democratic Republic of the"),
	COG	("COG","178","刚果（布） Congo"),
	COL	("COL","170","哥伦比亚 Colombia"),
	CRI	("CRI","188","哥斯达黎加 Costa Rica"),
	GRD	("GRD","308","格林纳达 Grenada"),
	GRL	("GRL","304","格陵兰 Greenland"),
	GEO	("GEO","268","格鲁吉亚 Georgia"),
	CUB	("CUB","192","古巴 Cuba"),
	GLP	("GLP","312","瓜德罗普Guadeloupe"),
	GUM	("GUM","316","关岛 Guam"),
	GUY	("GUY","328","圭亚那 Guyana"),
	KAZ	("KAZ","398","哈萨克斯坦Kazakhstan"),
	HTI	("HTI","332","海地 Haiti"),
	KOR	("KOR","410","韩国 Korea,Republic of"),
	NLD	("NLD","528","荷兰 Netherlands"),
	ANT	("ANT","530","荷属安的列斯 Netherlands Antilles"),
	HMD	("HMD","334","赫德岛和麦克唐纳岛 Heard islands and Mc Donald Islands"),
	HND	("HND","340","洪都拉斯Honduras"),
	KIR	("KIR","296","基里巴斯Kiribati"),
	DJI	("DJI","262","吉布提 Djibouti"),
	KGZ	("KGZ","417","吉尔吉斯斯坦 Kyrgyzstan"),
	GIN	("GIN","324","几内亚 Guinea"),
	GNB	("GNB","624","几内亚比绍 Guine-bissau"),
	CAN	("CAN","124","加拿大 Canada"),
	GHA	("GHA","288","加纳 Ghana"),
	GAB	("GAB","266","加蓬 Gabon"),
	KHM	("KHM","116","柬埔寨 Cambodia"),
	CZE	("CZE","203","捷克 Czech Repoublic"),
	ZWE	("ZWE","716","津巴布韦 Zimbabwe"),
	CMR	("CMR","120","喀麦隆 Cameroon"),
	QAT	("QAT","634","卡塔尔 Qatar"),
	CYM	("CYM","136","开曼群岛 Cayman Islands"),
	CCK	("CCK","166","科科斯(基林)群岛 Cocos(Keeling) Islands"),
	COM	("COM","174","科摩罗 Comoros"),
	CIV	("CIV","384","科特迪瓦 Coted'Ivoire"),
	KWT	("KWT","414","科威特 Kuwait"),
	HRV	("HRV","191","克罗地亚 Croatia"),
	KEN	("KEN","404","肯尼亚 Kenya"),
	COK	("COK","184","库克群岛 Cook Islands"),
	LVA	("LVA","428","拉脱维亚 Latvia"),
	LSO	("LSO","426","莱索托 Lesotho"),
	LAO	("LAO","418","老挝 Lao"),
	LBN	("LBN","422","黎巴嫩 Lebanon"),
	LBR	("LBR","430","利比里亚 Liberia"),
	LBY	("LBY","434","利比亚 Libya"),
	LTU	("LTU","440","立陶宛 Lithuania"),
	LIE	("LIE","438","列支敦士登Liechtenstein"),
	REU	("REU","638","留尼汪 Reunion"),
	LUX	("LUX","442","卢森堡 Luxembourg"),
	RWA	("RWA","646","卢旺达 Rwanda"),
	ROM	("ROM","642","罗马尼亚 Romania"),
	MDG	("MDG","450","马达加斯加 Madagascar"),
	MLT	("MLT","470","马耳他 Malta"),
	MDV	("MDV","462","马尔代夫 Maldives"),
	FLK	("FLK","238","福克兰群岛（马尔 维纳斯群岛） Falkland Islands ( Malvinas)"),
	MWI	("MWI","454","马拉维 Malawi"),
	MYS	("MYS","458","马来西亚 Malaysia"),
	MLI	("MLI","466","马里 Mali"),
	MKD	("MKD","807","前南马其顿 	MACEDONIA,THE 	FORMER YUGOSLAV	 REPUBLIC OF"),
	MHL	("MHL","584","马绍尔群岛 Marshall Islands"),
	MTQ	("MTQ","474","马提尼克 Martinique"),
	MYT	("MYT","175","马约特 Mayotte"),
	MUS	("MUS","480","毛里求斯 Mauritius"),
	MRT	("MRT","478","毛里塔尼亚 Mauritania"),
	USA	("USA","840","美国 United States"),
	ASM	("ASM","16","美属萨摩亚	 American Samoa"),
	UMI	("UMI","581","美国本土外小岛屿	 United States Minor Outlying Islands"),
	VIR	("VIR","850","美属维尔京群岛 United States Virgin Is-lands"),
	MNG	("MNG","496","蒙古 Mongolia"),
	MSR	("MSR","500","蒙特塞拉特 Montserrat"),
	BGD	("BGD","50","孟加拉国 Bangladesh"),
	PER	("PER","604","秘鲁 Peru"),
	FSM	("FSM","583","密克罗尼西亚联邦 Micronesia，Federated states of"),
	MMR	("MMR","104","缅甸 Myanmar"),
	MDA	("MDA","498","摩尔多瓦 Moldova"),
	MAR	("MAR","504","摩洛哥 Morocco"),
	MCO	("MCO","492","摩纳哥 Monaco"),
	MOZ	("MOZ","508","莫桑比克 Mozambique"),
	MEX	("MEX","484","墨西哥 Mexico"),
	NAM	("NAM","516","纳米比亚 Namibia"),
	ZAF	("ZAF","710","南非 South Africa"),
	ATA	("ATA","10","南极洲 Antarctica"),
	SGS	("SGS","239","南乔治亚岛和南桑	 德韦奇岛 South	 Georgia and South Sandwich Islands"),
	SCG	("SCG","349","塞尔维亚和黑山 Serbia and Montenegro"),
	NRU	("NRU","520","瑙鲁 Nauru"),
	NPL	("NPL","524","尼泊尔 Nepal"),
	NIC	("NIC","558","尼加拉瓜 Nicaragua"),
	NER	("NER","562","尼日尔 Niger"),
	NGA	("NGA","566","尼日利亚 Nigeria"),
	NIU	("NIU","570","纽埃 Niue"),
	NOR	("NOR","578","挪威 Norway"),
	NFK	("NFK","574","诺福克岛 Norfolk Island"),
	PCN	("PCN","612","皮特凯恩 Pitcairn"),
	PRT	("PRT","620","葡萄牙 Portugal"),
	JPN	("JPN","392","日本 Japan"),
	SWE	("SWE","752","瑞典 Sweden"),
	CHE	("CHE","756","瑞士 Switzerland"),
	SLV	("SLV","222","萨尔瓦多 El Salvador"),
	SLE	("SLE","694","塞拉利昂 Sierra leone"),
	SEN	("SEN","686","塞内加尔 Senegal"),
	CYP	("CYP","196","塞浦路斯 Cyprus"),
	SYC	("SYC","690","塞舌尔 Seychells"),
	SAU	("SAU","682","沙竺阿拉伯 Saudi Arabia"),
	CXR	("CXR","162","圣诞岛 Christmas Island"),
	STP	("STP","678","圣多美和普林西比	 Sao Tome and Principe"),
	SHN	("SHN","654","圣赫勒拿 Saint helena"),
	KNA	("KNA","659","圣基茨和尼维斯 Saint Kitts and nevis"),
	LCA	("LCA","662","圣卢西亚 Saint lucia"),
	SMR	("SMR","674","圣马力诺 San Marion"),
	SPM	("SPM","666","圣皮埃尔和密克隆	 Saint Pierre and Miquelon"),
	VCT	("VCT","670","圣文森特和格林纳	 丁斯 Saint Vincent and the Grenadines"),
	LKA	("LKA","144","斯里兰卡 Sri Lanka"),
	SVK	("SVK","703","斯洛伐克 Slovakia"),
	SVN	("SVN","705","斯洛文尼亚 Slovenia"),
	SJM	("SJM","744","斯瓦尔巴岛和扬马 延岛 Svalbard and jan Mayen Islands"),
	SWZ	("SWZ","748","斯威士兰 Swaziland"),
	SDN	("SDN","736","苏丹 Sudan"),
	SUR	("SUR","740","苏里南 Suriname"),
	SOM	("SOM","706","索马里 Somalia"),
	SLB	("SLB","90","所罗门群岛 Solomon Islands"),
	TJK	("TJK","762","塔吉克斯坦 Tajikistan"),
	THA	("THA","764","泰国 Thailand"),
	TZA	("TZA","834","坦桑尼亚 Tanzania"),
	TON	("TON","776","汤加 Tonga"),
	TCA	("TCA","796","特克斯科斯群岛 Turks and Caicos Islands"),
	TTO	("TTO","780","特立尼达和多巴哥 Trinidad and Tobago"),
	TUN	("TUN","788","突尼斯 Tunisia"),
	TUV	("TUV","798","图瓦卢 Tuvalu"),
	TUR	("TUR","792","土耳其 Turkey"),
	TKM	("TKM","795","土库曼斯坦Turkmenistan"),
	TKL	("TKL","772","托克劳 Tokelau"),
	WLF	("WLF","876","瓦利斯和富图纳 Wallis and Futuna"),
	VUT	("VUT","548","瓦努阿图 Vanuatu"),
	GTM	("GTM","320","危地马拉 Guatemala"),
	VEN	("VEN","862","委内瑞拉 Venezuela"),
	BRN	("BRN","96","文莱 Brunei Darussalam"),
	UGA	("UGA","800","乌干达 Uganda"),
	UKR	("UKR","804","乌克兰 Ukraine"),
	URY	("URY","858","乌拉圭 Uruguay"),
	UZB	("UZB","860","乌兹别克斯坦 Uzbekistan"),
	ESP	("ESP","724","西班牙 Spain"),
	ESH	("ESH","732","西撒哈拉 Western Sahara"),
	WSM	("WSM","882","萨摩亚 Samoa"),
	GRC	("GRC","300","希腊 Greece"),
	HKG	("HKG","344","香港 Hong Kong"),
	SGP	("SGP","702","新加坡 Singapore"),
	NCL	("NCL","540","新喀里多尼亚 New Caledonia"),
	NZL	("NZL","554","新西兰 New Zealand"),
	HUN	("HUN","348","匈牙利 Hungary"),
	SYR	("SYR","760","叙利亚 Syria"),
	JAM	("JAM","388","牙买加 Jamaica"),
	ARM	("ARM","51","亚美尼亚 Armenia"),
	YEM	("YEM","887","也门 Yemen"),
	IRQ	("IRQ","368","伊拉克 Iraq"),
	IRN	("IRN","364","伊朗 Iran"),
	ISR	("ISR","376","以色列 Israel"),
	ITA	("ITA","380","意大利 Italy"),
	IND	("IND","356","印度 India"),
	IDN	("IDN","360","印度尼西亚 Indonesia"),
	GBR	("GBR","826","英国 United Kingdom"),
	VGB	("VGB","92","英属维尔京群岛British Virgin Islands"),
	IOT	("IOT","86","英属印度洋领地 	British indian Ocean Territory"),
	JOR	("JOR","400","约旦 Jordan"),
	VNM	("VNM","704","越南 Viet Nam"),
	ZMB	("ZMB","894","赞比亚 Zambia"),
	TCD	("TCD","148","乍得 Chad"),
	GIB	("GIB","292","直布罗陀 Gibraltar"),
	CHL	("CHL","152","智利 Chile"),
	CAF	("CAF","140","中非 Central Africa"),
	CHN	("CHN","156","中国 China"),
	TWN	("TWN","158","中国台湾 Taiwan, China"),
	ZZZ	("ZZZ","999","其他");

	private String code;
	private String dCode;
	private String desc;
	
	CountryCodeEnum( String code,String dCode,String desc){
		this.code=code;
		this.desc=desc;
		this.dCode=dCode;
	}
	
	
	public static boolean isExist(String code){
		CountryCodeEnum[] countryCodes=CountryCodeEnum.values();
		for(CountryCodeEnum countryCode:countryCodes){
			if(countryCode.getCode().equals(code)){
				return true;
			}
		}
		return false;
	}
	

	public String getCode() {
		return code;
	}

	public String getdCode() {
		return dCode;
	}


	public String getDesc() {
		return desc;
	}

}
