/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.idealunited.gateway.dao;

import java.util.List;

import com.idealunited.gateway.model.GatewayResponse;
import com.idealunited.inf.dao.BaseDAO;

public interface GatewayResponseDAO extends BaseDAO<GatewayResponse> {

	public void updateSuccessByOrderNo(GatewayResponse gatewayResponse);

	public void updateFailByOrderNo(GatewayResponse gatewayResponse);

	public boolean updateSuccessByResponseNo(Long responseNo);

	public boolean updateFailByResponseNo(Long responseNo);

	public List<GatewayResponse> queryByOrderNo(Long tradeOrderNo);
}