/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.idealunited.gateway.dao;

import com.idealunited.gateway.model.GatewayRequest;
import com.idealunited.inf.dao.BaseDAO;

public interface GatewayRequestDAO extends BaseDAO<GatewayRequest> {

	/**
	 * 
	 * @param memberCode
	 * @param orderId
	 * @return
	 */
	GatewayRequest queryGatewayRequest(Long memberCode, String orderId);
}