/**
 *
 * auto generated by ibatis tools 
 *
 **/
package com.idealunited.gateway.model;

/**
 * GATEWAY_RESPONSE
 */

public class GatewayResponse implements java.io.Serializable {

	private Long id;
	private java.util.Date lastNotifyTime;
	private String orderId;
	private String pageUrl;
	private Long notifySuccessCount;
	private Long signType;
	private String responseContext;
	private String partnerId;
	private java.util.Date requestArrivalTime;
	private String serviceVersion;
	private String businessType;
	private Long lastNotifyState;
	private String bgUrl;
	private String signMsg;
	private String errorCode;
	private Long notifyFailCount;
	private String returnStatus;
	private java.util.Date createDate;
	private Long orderNo;

	public Long getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public java.util.Date getLastNotifyTime() {
		return lastNotifyTime;
	}

	public void setLastNotifyTime(java.util.Date lastNotifyTime) {
		this.lastNotifyTime = lastNotifyTime;
	}

	public String getPageUrl() {
		return pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	public Long getNotifySuccessCount() {
		return notifySuccessCount;
	}

	public void setNotifySuccessCount(Long notifySuccessCount) {
		this.notifySuccessCount = notifySuccessCount;
	}

	public Long getSignType() {
		return signType;
	}

	public void setSignType(Long signType) {
		this.signType = signType;
	}

	public String getResponseContext() {
		return responseContext;
	}

	public void setResponseContext(String responseContext) {
		this.responseContext = responseContext;
	}

	public String getPartnerId() {
		return partnerId;
	}

	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	public java.util.Date getRequestArrivalTime() {
		return requestArrivalTime;
	}

	public void setRequestArrivalTime(java.util.Date requestArrivalTime) {
		this.requestArrivalTime = requestArrivalTime;
	}

	public String getServiceVersion() {
		return serviceVersion;
	}

	public void setServiceVersion(String serviceVersion) {
		this.serviceVersion = serviceVersion;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public Long getLastNotifyState() {
		return lastNotifyState;
	}

	public void setLastNotifyState(Long lastNotifyState) {
		this.lastNotifyState = lastNotifyState;
	}

	public String getBgUrl() {
		return bgUrl;
	}

	public void setBgUrl(String bgUrl) {
		this.bgUrl = bgUrl;
	}

	public String getSignMsg() {
		return signMsg;
	}

	public void setSignMsg(String signMsg) {
		this.signMsg = signMsg;
	}

	public String getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public Long getNotifyFailCount() {
		return notifyFailCount;
	}

	public void setNotifyFailCount(Long notifyFailCount) {
		this.notifyFailCount = notifyFailCount;
	}

	public String getReturnStatus() {
		return returnStatus;
	}

	public void setReturnStatus(String returnStatus) {
		this.returnStatus = returnStatus;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

}